domain: flatronis.test
parallax:
  - file: assets/img/parallax/parallax-1.webp
    fallback: assets/img/parallax/parallax-1.png
    alt: logo lower layer
    speed: -5.5
  - file: assets/img/parallax/parallax-2.webp
    fallback: assets/img/parallax/parallax-2.png
    alt: logo upper layer
    speed: -4
  - file: assets/img/parallax/parallax-3.webp
    fallback: assets/img/parallax/parallax-3.png
    alt: logo text
    speed: -2
