# Domain of your blog
domain: erronis.games

# Name of your blog
name: Erronis Games

# How many posts per page do you want? Use 0 for infinity
posts: 6

# List layers of the parallax on home page
parallax:
  - file: assets/img/parallax/parallax-1.webp    # Base file
    fallback: assets/img/parallax/parallax-1.png # Fallback file in a more common format. Comment out if not needed
    alt: logo lower layer                        # Alternative text for accessibility
    speed: -5.5                                  # Scrolling speed
  - file: assets/img/parallax/parallax-2.webp
    fallback: assets/img/parallax/parallax-2.png
    alt: logo upper layer
    speed: -4
  - file: assets/img/parallax/parallax-3.webp
    fallback: assets/img/parallax/parallax-3.png
    alt: logo text
    speed: -2

# Add buttons to your navbar
navbar:
  main:
#    - text: My CV                               # Text to show on the button
#      link: https://johnsmith.cv/my-cv.pdf      # Link

  social:
    - image: assets/img/social/twitter.webp    # Base file
      fallback: assets/img/social/twitter.png  # Fallback file in a more common format. Comment out if not needed
      alt: Twitter bird logo                   # Alternative text for accessibility
      link: https://twitter.com/ErronisGames   # Link
    - image: assets/img/social/youtube.webp
      fallback: assets/img/social/youtube.png
      alt: YouTube button logo
      link: https://www.youtube.com/channel/UC0jnS_9ERShjqjW6rsgXoHA
